### ISSUE TITLE
Document the magic JVM flag to reduce CPU contention etc

### ISSUE THREAD

**Issue by tallpsmith** [performancecopilot/parfait#10]
This issue stems from the discovery many moons ago that for older Java+Linux Kernal combinations some of the Thread CPU metric collections were INSANELY SLOW.

To work around this, an evilly hidden JVM option was discovered: `-XX:+UseLinuxPosixThreadCPUClocks`

Which when active, drastically improved performance.

**Comment by myllynen** [comment]
Since the option is enabled by default on OpenJDK 1.7+ perhaps this issue can be closed?

**Comment by pwinckles** [comment]
The flag has been on by default since java 7 and is now deprecated for removal.

https://bugs.openjdk.org/browse/JDK-8338947
