### ISSUE TITLE
Requesting for a new release

### ISSUE THREAD

**Issue by yeshwanthponnusamy** [performancecopilot/parfait#108]
Hii Team,

We are using this FOSS in our product and we need to upgrade to the latest one. we are able to see there are some changes and the last change was on 2022 but the release we are able to see releases till 2021 (release 1.1.1). So can we get the latest release??

**Comment by natoscott** [comment]
@yeshwanthponnusamy I think it would be a good idea to review the security issues and update package deps first - can you do that and open a PR.

https://github.com/performancecopilot/parfait/security/dependabot

**Comment by yeshwanthponnusamy** [comment]
We could see these vulnerabilities which are there in the following link:
https://mvnrepository.com/artifact/io.pcp/parfait/1.1.1

Since i am not fully aware about all these dependency JARs, can you fix these vulnerabilities and give a release?

**Comment by yeshwanthponnusamy** [comment]
Hello Team,

I hope this message finds you well. I wanted to follow up on my previous request to give a new release for Parfait. I understand that you may have a busy schedule and numerous responsibilities, but I'm excited about the enhancements and bug fixes in this release and believe it would benefit the community.

**Comment by natoscott** [comment]
@yeshwanthponnusamy Parfait currently lacks an active maintainer.  We'll need to find one before a new release can happen, otherwise I guess we'll need to archive this project at some point if noone steps forward.

**Comment by pwinckles** [comment]
1.2.0 was released last December.

https://github.com/performancecopilot/parfait/releases/tag/1.2.0
