### ISSUE TITLE
Migrate the javax.measure stuff to JSR 363

### ISSUE THREAD

**Issue by tallpsmith** [performancecopilot/parfait#12]
_From [tallpsm...@gmail.com](https://code.google.com/u/114564928965221180928/) on June 26, 2014 07:36:41_

We currently use JSR 275 for units of measure, but that JSR has been rejected.  Instead we should migrate to the JSR 363.  On advice from the spec lead:

275 has been rejected 4 years ago. It was always feature-complete, e.g. GeoAPI has also since added it to an official OGC standard, but the JSR was non-final from a JCP point.
We currently see more momentum around 363 also from JUGs and the EC, so this time fingers crossed it'll be final, and at leas then certainly supersedes 275 or the Unit-API 0.6 (which we published under unitsofmeasurement.org so far)

Please add www.unitsofmeasurement.org. The domain host doesn't allow a wildcard, I also heard something similar from a host for a domain of myself, but this one was registered by fellow Spec Lead Jean-Marie Dautelle. unitsofmeasurement.github.io does not require a "www" in fact it likely won't work, but the .org domain currently does.

Cheers,
Werner

_Original issue: http://code.google.com/p/parfait/issues/detail?id=12_

**Comment by keilw** [comment]
Just a quick heads-up, JSR 363 passed PR this week: https://jcp.org/en/jsr/results?id=5837
So it's already more legitimate than JSR 275 which failed that stage ever was or will be.

**Comment by natoscott** [comment]
Parfait has (just now, in the master branch) switched from JSR-275 to using JSR-363 via the reference implementation.  Will be in parfait-0.4 soon.
