### ISSUE TITLE
Could systems-quantity be used for quantities like Information?

### ISSUE THREAD

**Issue by keilw** [performancecopilot/parfait#29]
I saw, Parfait 0.4 defines its own quantity types `Information` or `InformationRate`. While there's nothing wrong with that and exchanging data with other JSR-363 implementations or libraries in the same JVM may not happen much, could the small (4kB) Systems Quantity library be used instead, too?
https://github.com/unitsofmeasurement/uom-systems/tree/master/quantity

It is on jcenter http://jcenter.bintray.com/systems/uom/systems-quantity/ but if that makes it easier, we're happy to publish it on MavenCentral, too.

**Comment by natoscott** [comment]
@keilw yes, definitely!  I used this approach for simplicity initially (there was some issue accessing some of the NonSI classes ... but the exact issue eludes me now), and its been on my list of things to revisit.  Please feel free to send a pull request in the meantime, otherwise I'll return to it as soon as I'm able.  Thanks!

**Comment by keilw** [comment]
Will have a look, but these changes may only be reflected from Unit-API and RI 0.9 on (types like `Unit` and others should be nearly unchanged, we refactored the SPI, but I don't know if Parfait uses it)
https://github.com/unitsofmeasurement/uom-systems/issues/36 is a ticket to make `NonSI` public again, so it may contain certain units outside the SI system like Bar, Roentgen, etc. So in the end either the "common" module or another Unit System module (possibly Unicode but it may have more dependencies) would also be required. When is Parfait 0.4 due? We expect the Final Draft (0.9) of JSR 363 very soon, target date is end of this month, so within 2 weeks. Would that be OK or rather wait for the next version of Parfait?

**Comment by natoscott** [comment]
> we refactored the SPI, but I don't know if Parfait uses it

Nope, doesn't use it.

> unitsofmeasurement/uom-systems#36 is a ticket to make NonSI public again

Ah yes, that looks very familiar - that is the issue I came across earlier.

> When is Parfait 0.4 due? 

Today.  :)

But, s'OK - we can update to the 0.9 UoM modules when available, and switch in use of the NonSI module at that time.  And follow it up with a parfait-0.5 using the new modules.

Thanks for all the pointers Werner, much appreciated - very insightful.

**Comment by keilw** [comment]
Ok, then depending on the timeline of Parfait 0.5 it may use either 0.9 (Final Draft) or 1.0 (the Final version which structurally should have no real difference but it follows the Final Approval Ballot by JCP EC, so it could be a bit into the next quarter)

**Comment by keilw** [comment]
We'll try to keep them in sync with ICU4J (http://icu-project.org/apiref/icu4j/com/ibm/icu/util/MeasureUnit.html multiples handled differently of course), but my best guess would be the Unicode module: https://github.com/unitsofmeasurement/uom-systems/tree/master/unicode As of now it should have no ties to any of the SI modules (if any then the quantity module)

**Comment by natoscott** [comment]
This has been fixed for awhile (thanks @keilw) and I'm just pushing some changes now to switch to the 1.0 variants of unitsofmeasurement modules in Parfait.
