### ISSUE TITLE
Resetting PcpMmvWriter does not clear all objects related to metrics

### ISSUE THREAD

**Issue by ryandoyle** [performancecopilot/parfait#38]
Calling `io.pcp.parfait.dxm.BasePcpWriter#reset` clears `metricData` but there are several references held on to `PcpMetricInfo`s, `InstanceDomain`s, `PcpString`s and `PcpValueInfo`s (`PcpValueInfo`s are cleared in `metricData` map but there is a reference held in the `perMetricByteBuffers` map).

Maps/arrays/stores are as follows:
```
io.pcp.parfait.dxm.BasePcpWriter#metricInfoStore
io.pcp.parfait.dxm.BasePcpWriter#instanceDomainStore
io.pcp.parfait.dxm.PcpMmvWriter#stringInfo
io.pcp.parfait.dxm.BasePcpWriter#perMetricByteBuffers
```
These data structures should also be cleared out when `#reset` is called. I'm more just making a note of this at the moment. I noticed this when working on MMV v2 support but haven't tackled this object leak as part of that issue. The patch set is already fairly large.

**Comment by pwinckles** [comment]
This was fixed in https://github.com/performancecopilot/parfait/pull/121

**Comment by pwinckles** [comment]
I take that back. Only the byte buffer leak has been fixed. `metricInfoStore` and `instanceDomainStore` don't leak. This leaves `stringInfo` still needing to be addressed.
