### ISSUE TITLE
Upgrade Parfait to support log4j2

### ISSUE THREAD

**Issue by tallpsmith** [performancecopilot/parfait#71]
Log4j1.2 is now end of life.  There are some key spots where Parfait uses Log4j's MDC context which will need to be migrated during the journey to Log4j2.

There are a few areas that we need to consider, and this might warrant separating these into a separate module (due to library dependencies).  We could also decide whether to continue to support log4j1.2 at all.

Areas affected:

- `io.pcp.parfait.timing.ThreadContext.MdcBridge`
- General use of log4j1.2 logging (`parfait-agent`, and `QuiescentRegistryListener`)

**Comment by natoscott** [comment]
Yeah, nah.  :-)  See commit #85
