### ISSUE TITLE
Streamline Log4j and SLF4J or replace SLF4J with Log4J2

### ISSUE THREAD

**Issue by keilw** [performancecopilot/parfait#73]
Several modules (at least 7) use SLF4J instead of Log4J.
However, `parfait-agent` and one class in partait-core (`QuiescentRegistryListener`) use Log4J directly.

Therefore either all should use SLF4J or see #71 SLF4J could be replaced with Log4J2 as well and the SLF4J dependency removed.

**Comment by tallpsmith** [comment]
I actually saw this myself, but the `parfait-agent` must actually have a working logging system - SLF4j is not an actual logging system, but an interface to hide what that logging system is..

We could argue that `parfait-agent` should use SLF4j, but it'll still need Log4j in some form to actually log something.

**Comment by tallpsmith** [comment]
One option would be to consider setting enforcement to ban the use of _direct_ Log4j (overridden for certain modules).  I think this could be done with the PMD plugin.

**Comment by natoscott** [comment]
This has been resolved via #85
